FROM node:14

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY index.js index.js

RUN npm i

# ENTRYPOINT [ "executable" ]
CMD [ "npm", "start" ]
# CMD npm start